# Generated by Django 6.0.5 on 2026-09-30 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("visitors", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyGeoCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("country", models.CharField(blank=True, default="", max_length=80)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("views", models.PositiveIntegerField(default=0)),
                ("visitors", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "country_code", "city"),
                        name="dashboard_daily_geo_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyPageCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("path", models.CharField(max_length=255)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "path"), name="dashboard_daily_page_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("digest", models.CharField(max_length=64)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "digest"), name="dashboard_daily_visitor_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=40)),
                ("target", models.CharField(max_length=200)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSuspension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, default="", max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspension",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("object_id", models.PositiveBigIntegerField()),
                ("snapshot", models.TextField(blank=True, default="")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "スパム・宣伝"),
                            ("harassment", "嫌がらせ・誹謗中傷"),
                            ("inappropriate", "不適切な内容 (暴力・性的など)"),
                            ("privacy", "個人情報の掲載"),
                            ("rights", "著作権などの権利侵害"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="", max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "未対応"),
                            ("resolved", "対応済み"),
                            ("dismissed", "問題なし"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "通報",
                "verbose_name_plural": "通報",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "object_id"], name="dashboard_r_kind_c95fc0_idx"
                    ),
                    models.Index(
                        fields=["status"], name="dashboard_r_status_6e311f_idx"
                    ),
                ],
            },
        ),
    ]
