# Generated by Django 6.0.5 on 2026-05-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_track_apple_music_url',
            field=models.URLField(blank=True, default='', verbose_name='Apple Music リンク'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_track_artist',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='アーティスト名'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_track_image_url',
            field=models.URLField(blank=True, default='', verbose_name='ジャケット画像URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_track_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='お気に入りの曲名'),
        ),
    ]
