# Generated by Django 6.0.5 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_favorite_track_apple_music_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_track_preview_url',
            field=models.URLField(blank=True, default='', verbose_name='プレビュー音源URL'),
        ),
    ]
