# Generated by Django 6.0.5 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_favorite_track_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_track_apple_music_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Apple Music 曲ID'),
        ),
    ]
