# Generated by Django 6.0.5 on 2026-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_favorite_track_apple_music_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apple_user_id',
            field=models.CharField(blank=True, default='', help_text='Sign in with Apple の sub 識別子', max_length=255, verbose_name='Apple User ID'),
        ),
    ]
