# Generated by Django 6.0.5 on 2026-09-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_apple_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='未入力の場合はユーザー名が表示されます。', max_length=50, verbose_name='表示名'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='拠点'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='ウェブサイト'),
        ),
    ]
