# Generated by Django 6.0.5 on 2026-10-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_public_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="avatars/%Y/%m/", verbose_name="ユーザー画像"
            ),
        ),
    ]
