# Generated by Django 6.0.5 on 2026-10-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="notify_mentions_by_email",
            field=models.BooleanField(
                default=True,
                help_text="コメントやメッセージで @ユーザー名 と書かれたときにメールを受け取ります。",
                verbose_name="メンションをメールで通知",
            ),
        ),
    ]
