# Generated by Django 6.0.5 on 2026-10-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_notify_mentions_by_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="color_scheme",
            field=models.CharField(
                choices=[
                    ("midnight", "ミッドナイト"),
                    ("ocean", "オーシャン"),
                    ("forest", "フォレスト"),
                    ("ember", "エンバー"),
                    ("sakura", "サクラ"),
                    ("amethyst", "アメジスト"),
                ],
                default="midnight",
                max_length=20,
                verbose_name="カラースキーム",
            ),
        ),
    ]
