# Generated by Django 6.0.5 on 2026-10-06 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_customuser_color_scheme"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="した人の名前",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("mention", "メンション"),
                            ("comment", "コメント"),
                            ("reply", "返信"),
                        ],
                        max_length=10,
                        verbose_name="種類",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[
                            ("blog", "ブログ"),
                            ("lounge", "Lounge"),
                            ("wanderlens", "WanderLens"),
                        ],
                        max_length=12,
                        verbose_name="場所",
                    ),
                ),
                (
                    "target_title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="題名"
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="抜粋"
                    ),
                ),
                ("url", models.CharField(max_length=500, verbose_name="リンク")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="既読日時"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="した人",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="受け取る人",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at"],
                        name="accounts_notif_unread_idx",
                    )
                ],
            },
        ),
    ]
