# Generated by Django 6.0.5 on 2026-07-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_seed_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='community/media/%Y/%m/', verbose_name='メディア'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', '画像'), ('video', '動画')], default='', max_length=10, verbose_name='メディアタイプ'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='テキスト'),
        ),
    ]
