# Generated by Django 6.0.5 on 2026-09-23 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/images/%Y/%m/', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ブログ画像',
                'verbose_name_plural': 'ブログ画像',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='タイトル')),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, verbose_name='サブタイトル')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/%Y/%m/', verbose_name='カバー画像')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='本文')),
                ('body_delta', models.JSONField(blank=True, default=dict, verbose_name='本文 (エディタデータ)')),
                ('template', models.CharField(choices=[('feature', 'フィーチャー'), ('classic', 'クラシック'), ('split', 'スプリット'), ('minimal', 'ミニマル')], default='classic', max_length=20, verbose_name='テンプレート')),
                ('accent', models.CharField(choices=[('#2997ff', 'ブルー'), ('#bf5af2', 'パープル'), ('#30d158', 'グリーン'), ('#ff9f0a', 'オレンジ'), ('#ff375f', 'ピンク'), ('#64d2ff', 'ティール')], default='#2997ff', max_length=7, verbose_name='アクセントカラー')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('published', '公開')], default='draft', max_length=10, verbose_name='ステータス')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='著者')),
            ],
            options={
                'verbose_name': 'ブログ記事',
                'verbose_name_plural': 'ブログ記事',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
