# Generated by Django 6.0.5 on 2026-09-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_blocks',
            field=models.JSONField(blank=True, default=dict, verbose_name='本文 (ブロック)'),
        ),
    ]
