# Generated by Django 6.0.5 on 2026-09-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_body_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_width',
            field=models.CharField(choices=[('standard', '標準'), ('narrow', '狭幅')], default='standard', max_length=10, verbose_name='表示幅'),
        ),
    ]
