# Generated by Django 6.0.5 on 2026-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_display_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='accent',
            field=models.CharField(choices=[('none', 'なし'), ('#2997ff', 'ブルー'), ('#bf5af2', 'パープル'), ('#30d158', 'グリーン'), ('#ff9f0a', 'オレンジ'), ('#ff375f', 'ピンク'), ('#64d2ff', 'ティール')], default='none', max_length=7, verbose_name='アクセントカラー'),
        ),
    ]
