# Generated by Django 6.0.5 on 2026-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comments_and_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body_blocks_en",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="本文 (ブロック・英語)"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="body_html_en",
            field=models.TextField(blank=True, default="", verbose_name="本文 (英語)"),
        ),
        migrations.AddField(
            model_name="post",
            name="subtitle_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=400,
                verbose_name="サブタイトル (英語)",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="タイトル (英語)"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="translated_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="英訳日時"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="translation_hash",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=64
            ),
        ),
    ]
