# Generated by Django 6.0.5 on 2026-05-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='説明')),
                ('image', models.ImageField(upload_to='photraveler/%Y/%m/', verbose_name='写真')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='経度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Anonymous', max_length=50, verbose_name='名前')),
                ('text', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photraveler.mappin')),
            ],
        ),
    ]
