# Generated by Django 6.0.5 on 2026-07-01 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photraveler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappin',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mappin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_pins', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='mappin',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='mappin',
            name='image',
            field=models.ImageField(blank=True, upload_to='photraveler/%Y/%m/', verbose_name='写真'),
        ),
    ]
