# Generated by Django 6.0.5 on 2026-09-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photraveler', '0003_assign_existing_pins_to_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappin',
            name='country',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='国'),
        ),
        migrations.AddField(
            model_name='mappin',
            name='place_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='場所の名前'),
        ),
        migrations.AddField(
            model_name='mappin',
            name='visited_on',
            field=models.DateField(blank=True, null=True, verbose_name='訪れた日'),
        ),
        migrations.CreateModel(
            name='PinPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photraveler/%Y/%m/', verbose_name='写真')),
                ('thumbnail', models.ImageField(blank=True, upload_to='photraveler/thumbs/%Y/%m/', verbose_name='サムネイル')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photraveler.mappin')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
