# Generated by Django 6.0.5 on 2026-09-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photraveler', '0005_move_pin_image_to_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappin',
            name='image',
        ),
    ]
